### PR TITLE
Added saurabhshwetabhsingh.md

### PR DESCRIPTION
**Pull request by saurabhshwetabhsingh**

### CODE REVIEW

**Comment by saurabhshwetabhsingh** [comment]
@rishabh-bansal Please review this PR

**Comment by rishabh-bansal** [comment]
@saurabhshwetabhsingh Please add the file to src/profiles directory.

**Comment by saurabhshwetabhsingh** [comment]
@rishabh-bansal done, please review my PR

**Comment by saurabhshwetabhsingh** [comment]
Thank you :)

**Pull request merged**
